
DROP SEQUENCE seq_persona;
DROP SEQUENCE seq_usuario;
DROP SEQUENCE seq_veterinario;
DROP SEQUENCE seq_especializacion;
DROP SEQUENCE seq_veterinario_especializacion;
DROP SEQUENCE seq_especie;
DROP SEQUENCE seq_raza;
DROP SEQUENCE seq_mascota;
DROP SEQUENCE seq_medicamento;
DROP SEQUENCE seq_mascota_medicamento;
DROP SEQUENCE seq_servicio;
DROP SEQUENCE seq_veterinario_servicio;
DROP SEQUENCE seq_cita;
DROP SEQUENCE seq_cita_servicio;
DROP SEQUENCE seq_historial_medico;
DROP SEQUENCE seq_receta;
DROP SEQUENCE seq_calificacion;
DROP SEQUENCE seq_pago;
DROP SEQUENCE seq_notificacion;

-- Secuencias para los ID auto-generados con incremento de 10
CREATE SEQUENCE seq_persona INCREMENT BY 10 START WITH 10;
CREATE SEQUENCE seq_usuario INCREMENT BY 10 START WITH 10;
CREATE SEQUENCE seq_veterinario INCREMENT BY 10 START WITH 10;
CREATE SEQUENCE seq_especializacion INCREMENT BY 10 START WITH 10;
CREATE SEQUENCE seq_veterinario_especializacion INCREMENT BY 10 START WITH 10;
CREATE SEQUENCE seq_especie INCREMENT BY 10 START WITH 10;
CREATE SEQUENCE seq_raza INCREMENT BY 10 START WITH 10;
CREATE SEQUENCE seq_mascota INCREMENT BY 10 START WITH 10;
CREATE SEQUENCE seq_medicamento INCREMENT BY 10 START WITH 10;
CREATE SEQUENCE seq_mascota_medicamento INCREMENT BY 10 START WITH 10;
CREATE SEQUENCE seq_servicio INCREMENT BY 10 START WITH 10;
CREATE SEQUENCE seq_veterinario_servicio INCREMENT BY 10 START WITH 10;
CREATE SEQUENCE seq_cita INCREMENT BY 10 START WITH 10;
CREATE SEQUENCE seq_cita_servicio INCREMENT BY 10 START WITH 10;
CREATE SEQUENCE seq_historial_medico INCREMENT BY 10 START WITH 10;
CREATE SEQUENCE seq_receta INCREMENT BY 10 START WITH 10;
CREATE SEQUENCE seq_calificacion INCREMENT BY 10 START WITH 10;
CREATE SEQUENCE seq_pago INCREMENT BY 10 START WITH 10;
CREATE SEQUENCE seq_notificacion INCREMENT BY 10 START WITH 10;


CREATE SEQUENCE seq_auditoria INCREMENT BY 1 START WITH 1;